personnel_index:
    path:     /
    defaults: { _controller: "HomeBundle:Personnel:index" }
    methods:  GET

personnel_show:
    path:     /{id}/show
    defaults: { _controller: "HomeBundle:Personnel:show" }
    methods:  GET

personnel_new:
    path:     /new
    defaults: { _controller: "HomeBundle:Personnel:new" }
    methods:  [GET, POST]

personnel_edit:
    path:     /{id}/edit
    defaults: { _controller: "HomeBundle:Personnel:edit" }
    methods:  [GET, POST]

personnel_delete:
    path:     /{id}/delete
    defaults: { _controller: "HomeBundle:Personnel:delete" }
    methods:  DELETE
