<?php

namespace HomeBundle\Repository;

/**
 * FamilleArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
