home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /home

not_connected:
    resource: "@NotConnectedBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /init
    
